on:
  schedule:  
  - cron:  '0 23 * * *'
  push:
    branches: [main, master]

name: data-refresh

jobs:
  data-refresh:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      
      - uses: r-lib/actions/setup-renv@v2
      
      - name: Run refresh script
        run: Rscript R/update-daily.R
      
      - name: Push data to repo
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config --global user.name 'Steven Pawley'
            git config --global user.email 'steven.pawley@aer.ca'
            git add data/airdata-daily.rds
            git commit -m "Auto refresh daily data"
            git push
          else
            echo "Nothing to commit..."
          fi