on:
  schedule:  
  - cron:  '59 * * * *'
  push:
    branches: [main, master]

name: data-refresh

jobs:
  data-refresh:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: r-lib/actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      
      - uses: r-lib/actions/setup-renv@v2
      
      - name: Run refresh script
        run: Rscript R/update-daily.R
      
      - name: Push data to repo
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config --global user.name 'Steven Pawley'
            git config --global user.email 'steven.pawley@aer.ca'
            git add .
            git commit -m "Auto update"
            git push
          else
            echo "Nothing to commit..."
          fi